package ga

import "net/url"

//WARNING: This file was generated. Do not edit.

//Screenview Hit Type
type Screenview struct {
}

//NewScreenview creates a new...
func NewScreenview() *Screenview {
	h := &Screenview{}
	return h
}

func (h *Screenview) addFields(v url.Values) error {
	return nil
}
