package ga

//WARNING: This file was generated. Do not edit.

import "net/url"

//Exception Hit Type
type Exception struct {
	// Specifies the description of an exception.
	Description string 	//@TODO string
	// Specifies whether the exception was fatal.
	IsExceptionFatal string 	//@TODO bool
}

func (h *Exception) addFields(v url.Values) error {
	if h.Description != "" {
		v.Add("exd", h.Description)
	}
	if h.IsExceptionFatal != "" {
		v.Add("exf", h.IsExceptionFatal)
	}
	return nil
}