package ga

//WARNING: This file was generated. Do not edit.

import "net/url"

//Event Hit Type
type Event struct {
	// Specifies the event category. Must not be empty.
	Category string 	//@TODO string
	// Specifies the event action.  Must not be empty.
	Action string 	//@TODO string
	// Specifies the event label.
	Label string 	//@TODO string
	// Specifies the event value. Values must be non-negative.
	Value string 	//@TODO int64
}

func (h *Event) addFields(v url.Values) error {
	if h.Category != "" {
		v.Add("ec", h.Category)
	}
	if h.Action != "" {
		v.Add("ea", h.Action)
	}
	if h.Label != "" {
		v.Add("el", h.Label)
	}
	if h.Value != "" {
		v.Add("ev", h.Value)
	}
	return nil
}