package ga

//WARNING: This file was generated. Do not edit.

import "net/url"
import "errors"

//Social Hit Type
type Social struct {
	// Specifies the social network, for example Facebook or Google
	// Plus.
	Network string
	// Specifies the social interaction action. For example on
	// Google Plus when a user clicks the +1 button, the social
	// action is 'plus'.
	Action string
	// Specifies the target of a social interaction. This value
	// is typically a URL but can be any text.
	ActionTarget string
}

func (h *Social) addFields(v url.Values) error {
	if h.Network != "" {
		v.Add("sn", h.Network)
	} else {
		return errors.New("Required field 'Network' is missing")
	}
	if h.Action != "" {
		v.Add("sa", h.Action)
	} else {
		return errors.New("Required field 'Action' is missing")
	}
	if h.ActionTarget != "" {
		v.Add("st", h.ActionTarget)
	} else {
		return errors.New("Required field 'ActionTarget' is missing")
	}
	return nil
}