package ga

import "net/url"

//WARNING: This file was generated. Do not edit.

//Social Hit Type
type Social struct {
	network      string
	action       string
	actionTarget string
}

//NewSocial creates a new...
func NewSocial(network string, action string, actionTarget string) *Social {
	h := &Social{
		network:      network,
		action:       action,
		actionTarget: actionTarget,
	}
	return h
}

func (h *Social) addFields(v url.Values) error {
	v.Add("sn", h.network)
	v.Add("sa", h.action)
	v.Add("st", h.actionTarget)
	return nil
}
