package ga

//WARNING: This file was generated. Do not edit.

import "net/url"
import "errors"

//Transaction Hit Type
type Transaction struct {
	// A unique identifier for the transaction. This value should
	// be the same for both the Transaction hit and Items hits
	// associated to the particular transaction.
	ID string
	// Specifies the affiliation or store name.
	Affiliation string
	// Specifies the total revenue associated with the transaction.
	// This value should include any shipping or tax costs.
	Revenue string
	// Specifies the total shipping cost of the transaction.
	Shipping string
	// Specifies the total tax of the transaction.
	Tax string
	// When present indicates the local currency for all transaction
	// currency values. Value should be a valid ISO 4217 currency
	// code.
	CurrencyCode string
}

func (h *Transaction) addFields(v url.Values) error {
	if h.ID != "" {
		v.Add("ti", h.ID)
	} else {
		return errors.New("Required field 'ID' is missing")
	}
	if h.Affiliation != "" {
		v.Add("ta", h.Affiliation)
	}
	if h.Revenue != "" {
		v.Add("tr", h.Revenue)
	}
	if h.Shipping != "" {
		v.Add("ts", h.Shipping)
	}
	if h.Tax != "" {
		v.Add("tt", h.Tax)
	}
	if h.CurrencyCode != "" {
		v.Add("cu", h.CurrencyCode)
	}
	return nil
}