package ga

//WARNING: This file was generated. Do not edit.

import "net/url"
import "errors"

//Item Hit Type
type Item struct {
	// A unique identifier for the transaction. This value should
	// be the same for both the Transaction hit and Items hits
	// associated to the particular transaction.
	ID string
	// Specifies the item name.
	Name string
	// Specifies the price for a single item / unit.
	Price string
	// Specifies the number of items purchased.
	Quantity string
	// Specifies the SKU or item code.
	Code string
	// Specifies the category that the item belongs to.
	Category string
	// When present indicates the local currency for all transaction
	// currency values. Value should be a valid ISO 4217 currency
	// code.
	CurrencyCode string
}

func (h *Item) addFields(v url.Values) error {
	if h.ID != "" {
		v.Add("ti", h.ID)
	} else {
		return errors.New("Required field 'ID' is missing")
	}
	if h.Name != "" {
		v.Add("in", h.Name)
	} else {
		return errors.New("Required field 'Name' is missing")
	}
	if h.Price != "" {
		v.Add("ip", h.Price)
	}
	if h.Quantity != "" {
		v.Add("iq", h.Quantity)
	}
	if h.Code != "" {
		v.Add("ic", h.Code)
	}
	if h.Category != "" {
		v.Add("iv", h.Category)
	}
	if h.CurrencyCode != "" {
		v.Add("cu", h.CurrencyCode)
	}
	return nil
}